#include <stdio.h>
#include <stdlib.h>
#include <stdbool.h>
#include "types/types.h"
#include "models/models.h"
#include "struct/structs.h"
#include "utils/utils.h"

#define SUCCESS 0

extern data_type_t DB_BYTE, DB_SHORT, DB_INT, DB_LONG, DB_FLOAT, DB_DOUBLE;
extern data_type_t DB_CHAR, DB_STRING, DB_TEXT, DB_DATE, DB_TIME;
extern function_t TODAY, COUNT, SUM, MIN, MAX, AVG, MEDIAN, MODE;

int main() {
	#define column_count 5
	char *keys[column_count] = { "id", "nombre", "apellido_mat", "apellido_pat", "fecha_nac" };
	column_t *columns[5] = {
		new_column(keys[0], MOD_PRIMARY_KEY + MOD_AUTOGENERATED, &DB_INT, AUTOINCREMENTAL, NULL),
		new_column(keys[1], MOD_REQUIRED, &DB_STRING, NO_GENERATOR, NULL),
		new_column(keys[2], MOD_REQUIRED, &DB_STRING, NO_GENERATOR, NULL),
		new_column(keys[3], MOD_OPTIONAL, &DB_STRING, NO_GENERATOR, NULL),
		new_column(keys[4], MOD_OPTIONAL + MOD_AUTOGENERATED, &DB_DATE, DEFAULT_VALUE, &TODAY)
	};
	table_t *tableUsers = new_table("Usuarios", column_count, columns);
	printf("%s\n", to_string(tableUsers));

	char *values[10][4] = {
		{"Brayan", "Tellez", "Cruz", "10-02-2005"},
		{"Pedro", "Tellez", NULL, NULL},
		{"_Juan", "Tellez", NULL, "12-02-2005"},
		{"Juan", "Tellez", "Cruz", "13-02-2006"},
		{"Maria", "Tellez", NULL, "14-02-2005"},
		{"Carlos", "Tellez", "Ramirez", "15-02-2003"},
		{"Ramon", "Tellez", "Ramirez", "16-02-2003"},
		{"Luis", "Tellez", "Cruz", "20-10-2003"},
		{"Jaime", "Tellez", "Perez", "18-02-2004"},
		{"Julian", "Tellez", "Cruz", "19-02-2004"},
	};

	#define row_count 10
	hash_map_t **rows = (hash_map_t**) malloc(row_count * sizeof(hash_map_t*));
	for(int i = 0; i < row_count; i++) {
		rows[i] = new_hash_map();
		for(int j = 1; j < column_count - 1; j++)
			hash_map_insert(rows[i], new_pair(keys[j], new_mdb_type(&DB_STRING, new_string(values[i][j - 1]))));
		hash_map_insert(rows[i], new_pair(keys[4], new_mdb_type(&DB_DATE, new_string(values[i][3]))));
	}
	result_t *result = table_insert(tableUsers, row_count, rows);
	if(!result->isSuccess) {
		printf("Ocurrio un error al realizar la insercion \"%s\".\n", result->error);
		return -1;
	}
	printf("Se han insertado %s filas.\n", to_string(result->value));

	condition_t *condition_all = new_condition(NO_OP, NULL, NULL);
	printf("SELECCIONAR * DE usuarios\n");
	result = table_select(*tableUsers, condition_all);
	if(result->isSuccess)
		show_table_select(*((select_table_t*) result->value));

	select_table_t selected = *((select_table_t*) result->value);
	result = table_group(selected, "apellido_pat");
	if(result->isSuccess)
		show_table_select(*((select_table_t*) result->value));

	linked_list_t *args = new_linked_list(STRING);
	linked_list_push(args, new_string("apellido_pat"));

	function_t *cloneFn = clone_object(&COUNT);
	function_set_alias(cloneFn, "Conteo_apellidos");
	cloneFn->args = args;

	linked_list_t *proyects = new_linked_list(UNKNOWN_TYPE);
	linked_list_push(proyects, cloneFn);
	linked_list_push(proyects, new_string("apellido_pat"));

	selected = *(select_table_t*)result->value;
	result = table_proyect(selected, *proyects);
	if(result->isSuccess)
		show_table_select(*((select_table_t*) result->value));
	/*
	condition_all = new_condition(
		OP_OR,
		new_condition(
			OP_XOR,
			new_condition(
				OP_LIKE,
				new_string(keys[1]),
				new_mdb_type(&DB_STRING, new_string("%u%"))
			),
			new_condition(
				OP_GREAT_EQUALS,
				new_string(keys[0]),
				new_mdb_type(&DB_INT, new_int(9))
			)
		),
		new_condition(
			OP_LESS_EQUALS,
			new_string(keys[4]),
			new_mdb_type(&DB_DATE, new_string("20-10-2003"))
		)
	);
	printf("SELECCIONAR * DE usuarios TAL QUE %s\n", to_string(condition_all));
	result = table_select(*tableUsers, condition_all);
	if(result->isSuccess)
		show_table_select(*((select_table_t*) result->value));
	else {
		printf("No existen elementos que coincidan con la condicion \"%s\"\n", result->error);
		return -1;
	}

	linked_list_t *proyects = new_linked_list(STRING);
	linked_list_push(proyects, new_string("id"));
	linked_list_push(proyects, new_string("fecha_nac"));
	result = table_proyect(selected, *proyects);
	if(result->isSuccess)
		show_table_select(*((select_table_t*) result->value));
	delete_linked_list(proyects);

	linked_list_t *args = new_linked_list(STRING);
	linked_list_push(args, new_string("apellido_pat"));

	function_t *cloneFn = clone_object(&COUNT);
	function_t *modeFn = clone_object(&MODE);
	function_set_alias(cloneFn, "Conteo_apellidos");
	cloneFn->args = args;
	modeFn->args = args;

	args = new_linked_list(STRING);
	linked_list_push(args, new_string("id"));
	function_t *sumFn = clone_object(&SUM);
	function_t *minFn = clone_object(&MIN);
	function_t *maxFn = clone_object(&MAX);
	function_t *avgFn = clone_object(&AVG);
//	function_t *medianFn = clone_object(&MEDIAN);
	sumFn->args = args;
	minFn->args = args;
	maxFn->args = args;
	avgFn->args = args;
//	medianFn->args = args;

	proyects = new_linked_list(UNKNOWN_TYPE);
	linked_list_push(proyects, cloneFn);
	linked_list_push(proyects, sumFn);
	linked_list_push(proyects, minFn);
	linked_list_push(proyects, maxFn);
	linked_list_push(proyects, avgFn);
//	linked_list_push(proyects, medianFn);
	linked_list_push(proyects, modeFn);
	result = table_proyect(selected, *proyects);
	if(result->isSuccess)
		show_table_select(*((select_table_t*) result->value));
	else {
		printf("[ERROR]: \"%s\"\n", result->error);
		return -1;
	}

	linked_list_t *replaces = new_linked_list(PAIR);
	linked_list_push(replaces, new_pair(keys[1], new_mdb_type(&DB_STRING, new_string("Uriel"))));
	condition_all = new_condition(
		OP_GREAT_EQUALS,
		new_string(keys[0]),
		new_mdb_type(&DB_INT, new_int(9))
	);
	printf("ACTUALIZAR usuarios REEMPLAZAR nombre = \"Uriel\" TAL QUE %s\n", to_string(condition_all));
	result = table_update(tableUsers, condition_all, replaces);
	printf("Se han actualizado %s filas.\n", to_string(result->value));

	condition_all = new_condition(NO_OP, NULL, NULL);
	printf("SELECCIONAR * DE usuarios\n");
	result = table_select(*tableUsers, condition_all);
	if(result->isSuccess)
		show_table_select(*((select_table_t*) result->value));

	condition_all = new_condition(
		OP_LESS,
		new_string(keys[0]),
		new_mdb_type(&DB_INT, new_int(5))
	);
	printf("ELIMINAR DE usuarios TAL QUE %s\n", to_string(condition_all));
	result = table_delete(tableUsers, condition_all);
	printf("Se han eliminado %s filas.\n", to_string(result->value));

	condition_all = new_condition(NO_OP, NULL, NULL);
	printf("SELECCIONAR * DE usuarios\n");
	result = table_select(*tableUsers, condition_all);
	if(result->isSuccess)
		show_table_select(*((select_table_t*) result->value));
	*/

	return SUCCESS;
}
/*
	mdb_type_t *byte_value = new_mdb_type(&DB_BYTE, new_char(234));
	mdb_type_t *short_value = new_mdb_type(&DB_SHORT, new_short(54300));
	mdb_type_t *int_value = new_mdb_type(&DB_INT, new_int(999999));
	mdb_type_t *long_value = new_mdb_type(&DB_LONG, new_long(1020304235));
	mdb_type_t *char_value = new_mdb_type(&DB_CHAR, new_char('C'));
	mdb_type_t *float_value = new_mdb_type(&DB_FLOAT, new_float(13.45));
	mdb_type_t *double_value = new_mdb_type(&DB_DOUBLE, new_double(1234.5412));
	mdb_type_t *string_value = new_mdb_type(&DB_STRING, new_string("Hola mundo."));
	mdb_type_t *text_value = new_mdb_type(&DB_TEXT, new_string("En la vida hay retos que no pueden ser superados solos, necesitamos el apoyo de alguien que este dispuesto a ayudarnos."));
	mdb_type_t *date_value = new_mdb_type(&DB_DATE, new_string("12-01-2024"));
	mdb_type_t *time_value = new_mdb_type(&DB_TIME, new_string("12:00:450"));

	char *mdb_type_string1 = to_string(byte_value);
	printf("Byte Value: %s\n", mdb_type_string1);
	char *mdb_type_string2 = to_string(short_value);
	printf("Short Value: %s\n", mdb_type_string2);
	char *mdb_type_string3 = to_string(int_value);
	printf("Int Value: %s\n", mdb_type_string3);
	char *mdb_type_string4 = to_string(long_value);
	printf("Long Value: %s\n", mdb_type_string4);
	char *mdb_type_string5 = to_string(char_value);
	printf("Char Value: %s\n", mdb_type_string5);
	char *mdb_type_string6 = to_string(float_value);
	printf("Float Value: %s\n", mdb_type_string6);
	char *mdb_type_string7 = to_string(double_value);
	printf("Double Value: %s\n", mdb_type_string7);
	char *mdb_type_string8 = to_string(string_value);
	printf("String Value: %s\n", mdb_type_string8);
	char *mdb_type_string9 = to_string(text_value);
	printf("%s\n", mdb_type_string9);
	char *mdb_type_string10 = to_string(date_value);
	printf("Date Value: %s\n", mdb_type_string10);
	char *mdb_type_string11 = to_string(time_value);
	printf("Time Value: %s\n", mdb_type_string11);

	const char *key = "KEY";
	pair_t *pair = new_pair(key, date_value);
	char *pair_string = to_string(pair);

	simple_node_t *node = new_simple_node(pair, PAIR);
	char *node_string = to_string(node);
	printf("Simple Node: %s\n", node_string);

	linked_list_t *list = new_linked_list(PAIR);
	for(int i = 0; i < 10; i++)
		linked_list_push(list, new_pair(key, new_mdb_type(&DB_INT, new_int(i))));
	char *list_string = to_string(list);
	printf("Linked List: %s\n", list_string);

	hash_map_t *hashMap = new_hash_map();
	char *keys[10] = { "id", "age", "a", "b", "c", "d", "name", "lastname", "email", "bornday" };
	for(int i = 0; i < 6; i++)
		hash_map_insert(hashMap, new_pair(keys[i], new_mdb_type(&DB_INT, new_int(i))));
	char *strings[4] = {"Brayan", "Tellez", "btellez@example.com", "10-02-2003"};
	for(int i = 6; i < 10; i++)
		hash_map_insert(hashMap, new_pair(keys[i], new_mdb_type(&DB_STRING, new_string(strings[i-6]))));
	char *hash_map_string = to_string(hashMap);
	printf("Hash Map: %s\n", hash_map_string);

	hash_map_t *hashMapFiltered = hash_map_filter(*hashMap, 2, "a", "b");
	char *hash_map2_string = to_string(hashMapFiltered);
	printf("Hash Map Filtered: %s\n", hash_map2_string);

	hash_map_t *hashMapFiltered2 = hash_map_filter(*hashMap, 2, "c", "d");
	hash_map_t *hashMapFiltered3 = hash_map_filter(*hashMap, 2, "a", "d");
	hash_map_t *hashMapJoined = hash_map_join(*hashMapFiltered, *hashMapFiltered2);
	char *hash_map3_string = to_string(hashMapJoined);
	printf("Hash Map Joined: %s\n", hash_map3_string);

	printf("Los Hash Maps %s y %s son %s\n",
		to_string(hashMapFiltered2), to_string(hashMapFiltered3),
		compare_hash_map(hashMapFiltered2, hashMapFiltered3) == EQUALS ? "Iguales" : "Diferentes");

	set_t *set1 = new_set(HASH_MAP);
	set_insert(set1, hashMapFiltered);
	set_insert(set1, hashMapFiltered2);
	char *set1_string = to_string(set1);
	printf("Set 1: %s\n", set1_string);

	hash_map_t *hashMapFiltered4 = hash_map_filter(*hashMap, 2, "a", "b");
	hash_map_t *hashMapFiltered5 = hash_map_filter(*hashMap, 2, "c", "d");
	hash_map_t *hashMapFiltered6 = hash_map_filter(*hashMap, 2, "a", "c");

	set_t *set2 = new_set(HASH_MAP);
	set_insert(set2, hashMapFiltered3);
	set_insert(set2, hashMapFiltered4);
	char *set2_string = to_string(set2);
	printf("Set 2: %s\n", set2_string);

	set_t *setUnion = set_union(*set1, *set2);
	char *set_union_string = to_string(setUnion);
	printf("Set Union: %s\n", set_union_string);

	set_t *setIntersection = set_intersection(*set1, *set2);
	char *set_intersection_string = to_string(setIntersection);
	printf("Set Intersection: %s\n", set_intersection_string);

	set_t *setDiference = set_diference(*set1, *set2);
	char *set_diference_string = to_string(setDiference);
	printf("Set diference: %s\n", set_diference_string);

	set_t *setExclusiveDiference = set_exclusive_diference(*set1, *set2);
	char *set_exclusive_diference_string = to_string(setExclusiveDiference);
	printf("Set exclusive diference: %s\n", set_exclusive_diference_string);

	set_t *setCrossProduct = set_cross_product(*set1, *set2);
	char *set_cross_product_string = to_string(setCrossProduct);
	printf("Set cross_product: %s\n", set_cross_product_string);

	binary_tree_t *tree = new_binary_tree(MDB_TYPE);
	char *values[10] = { "j", "x", "c", "m", "d", "k", "u", "l", "y", "f" };
	for(int i = 0; i < 10; i++)
		binary_tree_insert(tree, new_mdb_type(&DB_STRING, new_string(values[i])));
	char *tree_string = to_string(tree);
	printf("Binary Tree: %s\n", tree_string);

	result_t *resultFindBT = binary_tree_find(*tree, new_mdb_type(&DB_STRING, new_string(values[6])));
	if(resultFindBT->isSuccess)
		printf("Find in Binary Tree\n");
	else
		printf("%s\n", resultFindBT->error);

	resultFindBT = binary_tree_find(*tree, new_mdb_type(&DB_STRING, new_string("j")));
	if(resultFindBT->isSuccess)
		printf("Find in Binary Tree\n");
	else
		printf("%s\n", resultFindBT->error);

	binary_tree_delete(tree, new_mdb_type(&DB_STRING, new_string(values[6])));
	char *tree_string_deleted = to_string(tree);
	printf("Binary Tree: %s\n", tree_string_deleted);

	binary_tree_delete(tree, new_mdb_type(&DB_STRING, new_string(values[4])));
	char *tree_string_deleted2 = to_string(tree);
	printf("Binary Tree: %s\n", tree_string_deleted2);

	binary_tree_delete(tree, new_mdb_type(&DB_STRING, new_string(values[8])));
	char *tree_string_deleted3 = to_string(tree);
	printf("Binary Tree: %s\n", tree_string_deleted3);

	graph_t *graph = new_graph(STRING);
	for(int i = 0; i < 9; i++)
		graph_insert_node(graph, false);
	graph_insert_node(graph, true);

	int begin[10] = { 1, 1, 2, 3, 4, 4, 5, 6, 7, 9 };
	int end[10] = { 2, 3, 4, 4, 5, 6, 7, 7, 9, 10 };
	for(int i = 0; i < 10; i++)
		graph_insert_edge(graph, begin[i], end[i], values[i]);
	char *graph_string = to_string(graph);
	printf("Graph: %s\n", graph_string);
	*/
